---
title: "Solid Tumor Example"
author:
- name: Mark Chen
  affiliation: St Jude Children's Research Hospital
package: yamatClassifier
output:
  BiocStyle::html_document
abstract: |
  A workflow to develop a classifier of a subst of solid tumors.
vignette: |
  %\VignetteIndexEntry{Solid Tumor Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r load_lib, echo=FALSE}
library(yamat)
library(yamatClassifier)
library(ggplot2)
library(ggpubr)
```


# Data

```{r get_data}
# Download data
gse_acc <- "GSE97529"
data_dir <- "~/Downloads/GSE97529"
rgset <- yamat::get_gse(gse_acc, data_dir)
# Load pre-calculated.
#load(file.path(data_dir, "rgset.Rda"))
# Normalization
gmset <- yamat::normalize(rgset = rgset, norm_method = "swan")
# Beta values
beta_vals <- minfi::getBeta(gmset, offset = 100)
# Save
save(rgset, file = file.path(data_dir, "rgset.Rda"))
```

# Obtain the beta values of most variable loci

```{r most_variable_loci}
top_n <- 1000
beta_vals <- most_variably_methylated_loci(beta_vals, top_n = top_n)
```

```{r}
beta_sd <- rowSds(beta_vals)
names(beta_sd) <- rownames(beta_vals)
cutoff <- head(sort(beta_sd, decreasing = TRUE), top_n)[top_n]
data.frame(x = beta_sd) %>%
  ggdensity(
    .,
    x = "x",
    fill = "lightgray",
    add = "mean"
  ) + 
  geom_vline(xintercept = cutoff, linetype = "dotted", colour = "coral")
```


